"""
Guess the number that is generated by the computer
Author : Monisha Sivaraj
Date : 15/01/2021
"""

import random

def guessNumber(x):
    randomNumber = random.randint(1,x)
    guess = 0
    while guess != randomNumber:
        guess = int(input(f'Guess the number between 1 and {x}:'))
        print(guess)
        if guess < randomNumber :
            print("Sorry, you have guessed wrongly.Too Low value")
        elif guess > randomNumber :
            print("Sorry, you have guessed wrongly.Too High value")
    print("Yeah !!! Guessed correctly..")

guessNumber(10)